name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: https://registry.npmjs.org

    - uses: actions/cache@v1
      env:
        CACHE_NAME: cache-npm-packages
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-${{ env.CACHE_NAME }}-
          ${{ runner.OS }}-npm-
          ${{ runner.OS }}-

    - name: Install dependencies
      run: |
        npm ci
        npm run bootstrap
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

    - name: Test
      run: npm run test

    - name: Build
      run: npm run build

    - name: Publish to npm
      if: github.ref == 'refs/heads/master' && github.event_name == 'release' && github.event.action == 'created'
      run: |
        npm publish packages/atmention-core
        npm publish dist/atmention-angular
        npm publish dist/atmention-angularjs
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
