'use strict';

module.exports = {
  LABEL_TEMPLATE_LITERAL: '__LABEL__',
  VALUE_TEMPLATE_LITERAL: '__VALUE__',

  HIGHLIGHT_MENTION_CLASS: 'mention',
  HIGHLIGHT_SELECTION_CLASS: 'selection',
  HIGHLIGHT_SELECTION_START_CLASS: 'start',
  HIGHLIGHT_SELECTION_END_CLASS: 'end',
};
